import type { Order } from "@/modules/marketplace/types/marketplace.types";

export const mockOrders: Order[] = [
	{
		id: "1234",
		direction: "SELL_WETH",
		amount: 10.0,
		token: "WETH",
		delta: 50,
		minAmountOut: 25000,
		expiryHours: 5,
		expiryMinutes: 20,
	},
	{
		id: "1235",
		direction: "SELL_USDC",
		amount: 50000,
		token: "USDC",
		delta: -30,
		minAmountOut: 15.5,
		expiryHours: 3,
		expiryMinutes: 45,
	},
	{
		id: "1236",
		direction: "SELL_WETH",
		amount: 25.0,
		token: "WETH",
		delta: 75,
		minAmountOut: 60000,
		expiryHours: 8,
		expiryMinutes: 10,
	},
	{
		id: "1237",
		direction: "SELL_USDC",
		amount: 100000,
		token: "USDC",
		delta: -50,
		minAmountOut: 32.0,
		expiryHours: 2,
		expiryMinutes: 30,
	},
	{
		id: "1238",
		direction: "SELL_WETH",
		amount: 5.5,
		token: "WETH",
		delta: 25,
		minAmountOut: 15000,
		expiryHours: 6,
		expiryMinutes: 0,
	},
	{
		id: "1239",
		direction: "SELL_USDC",
		amount: 75000,
		token: "USDC",
		delta: -20,
		minAmountOut: 24.5,
		expiryHours: 4,
		expiryMinutes: 15,
	},
];
