/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresetRouteImport } from './routes/preset'
import { Route as MyTradesRouteImport } from './routes/my-trades'
import { Route as MyQuotesRouteImport } from './routes/my-quotes'
import { Route as IndexRouteImport } from './routes/index'

const PresetRoute = PresetRouteImport.update({
  id: '/preset',
  path: '/preset',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTradesRoute = MyTradesRouteImport.update({
  id: '/my-trades',
  path: '/my-trades',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQuotesRoute = MyQuotesRouteImport.update({
  id: '/my-quotes',
  path: '/my-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-quotes': typeof MyQuotesRoute
  '/my-trades': typeof MyTradesRoute
  '/preset': typeof PresetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-quotes': typeof MyQuotesRoute
  '/my-trades': typeof MyTradesRoute
  '/preset': typeof PresetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-quotes': typeof MyQuotesRoute
  '/my-trades': typeof MyTradesRoute
  '/preset': typeof PresetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-quotes' | '/my-trades' | '/preset'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-quotes' | '/my-trades' | '/preset'
  id: '__root__' | '/' | '/my-quotes' | '/my-trades' | '/preset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyQuotesRoute: typeof MyQuotesRoute
  MyTradesRoute: typeof MyTradesRoute
  PresetRoute: typeof PresetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preset': {
      id: '/preset'
      path: '/preset'
      fullPath: '/preset'
      preLoaderRoute: typeof PresetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trades': {
      id: '/my-trades'
      path: '/my-trades'
      fullPath: '/my-trades'
      preLoaderRoute: typeof MyTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-quotes': {
      id: '/my-quotes'
      path: '/my-quotes'
      fullPath: '/my-quotes'
      preLoaderRoute: typeof MyQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyQuotesRoute: MyQuotesRoute,
  MyTradesRoute: MyTradesRoute,
  PresetRoute: PresetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
