name: Deploy to Netlify

on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  NODE_VERSION: "20"
  VITE_VWAP_CONTRACT_ADDRESS: "0x61A73573A14898E7031504555c841ea11E7FB07F"
  VITE_VWAP_ORACLE_CONTRACT_ADDRESS: "0xd7D42352bB9F84c383318044820FE99DC6D60378"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          VITE_REOWN_PROJECT_ID: ${{ vars.VITE_REOWN_PROJECT_ID }}

      - uses: qbtf/action-netlify-cli@v2
        id: netlify
        with:
          args: deploy --json --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 9e33e929-ec66-4670-b3d1-e159a9f71dcd
